sudo: required
dist: trusty
addons:
    chrome: stable
language: node_js

node_js:
    - "8.10.0"

install:
  - npm install

cache:
  directories:
    - "node_modules"
    
script:
    - npm run lint
   
after_script:
    - npm run coveralls

